[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://mechgpt-nxzmb.ondigitalocean.app/api/:splat"
  status = 200